# Generated by Django 4.1.4 on 2023-01-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSpiders',
            fields=[
                ('course', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_Name', models.CharField(max_length=30)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jspiders')),
            ],
        ),
    ]
